# Generated by Django 5.2.17 on 2026-09-17 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_cuenta_pedido_cuenta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('transferencia', 'Transferencia')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.cuenta')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_positivo')],
            },
        ),
    ]
