# Generated by Django 5.2.17 on 2026-09-17 18:02

import django.db.models.deletion
import pedidos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoWebpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(default=pedidos.models.generar_orden_webpay, editable=False, max_length=26, unique=True)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('creado', 'Creado'), ('iniciado', 'Iniciado'), ('por_verificar', 'Por verificar'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado'), ('fallido', 'Fallido')], default='creado', max_length=20)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=32)),
                ('codigo_respuesta', models.IntegerField(blank=True, null=True)),
                ('tipo_pago', models.CharField(blank=True, max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_webpay', to='pedidos.cuenta')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intentos_webpay', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='intento_webpay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago_confirmado', to='pedidos.intentowebpay'),
        ),
        migrations.AddConstraint(
            model_name='intentowebpay',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='intento_webpay_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='intentowebpay',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['creado', 'iniciado', 'por_verificar'])), fields=('cuenta',), name='un_intento_webpay_activo_por_cuenta'),
        ),
    ]
