# Generated by Django 5.2.17 on 2026-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_intentowebpay_pago_intento_webpay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentowebpay',
            name='detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='fecha_transaccion',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='observacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='retorno_confirmable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='ultimos_digitos',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='url_webpay',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('transferencia', 'Transferencia'), ('webpay', 'Webpay Plus (integración)')], max_length=20),
        ),
    ]
