# Generated by Django 5.2.17 on 2026-09-18 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_intentowebpay_detalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='intentowebpay',
            name='un_intento_webpay_activo_por_cuenta',
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intentos_webpay', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='checkout_clave',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_clave',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos.cuenta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('sin_pagar', 'Pendiente de pago'), ('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='sin_pagar', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='intentowebpay',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['creado', 'iniciado', 'por_verificar']), ('pedido__isnull', True)), fields=('cuenta',), name='un_intento_webpay_activo_por_cuenta'),
        ),
        migrations.AddConstraint(
            model_name='intentowebpay',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['creado', 'iniciado', 'por_verificar']), ('pedido__isnull', False)), fields=('pedido',), name='un_intento_activo_por_pedido'),
        ),
    ]
