# Generated by Django 5.2.17 on 2026-09-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_intentowebpay_un_intento_webpay_activo_por_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentowebpay',
            name='cancelacion_solicitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='formulario_abierto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentowebpay',
            name='reintento_de',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siguiente_intento', to='pedidos.intentowebpay'),
        ),
    ]
