# Generated by Django 5.2.17 on 2026-09-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_mayoria_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='opciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
