# Generated by Django 5.2.17 on 2026-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_detallepedido_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
