# Generated by Django 5.2.17 on 2026-09-29 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0003_producto_requiere_mayoria_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requerido', models.BooleanField(default=False)),
                ('seleccion_multiple', models.BooleanField(default=False, verbose_name='permite varias opciones')),
                ('max_selecciones', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='máximo de selecciones')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_opciones', to='carta.producto')),
            ],
            options={
                'verbose_name': 'grupo de opciones',
                'verbose_name_plural': 'grupos de opciones',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OpcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_extra', models.DecimalField(decimal_places=0, default=0, help_text='Recargo en pesos chilenos. Usa 0 si no cambia el precio.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='carta.grupoopcion')),
            ],
            options={
                'verbose_name': 'opción de producto',
                'verbose_name_plural': 'opciones de productos',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='grupoopcion',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='carta_grupo_nombre_unico_producto'),
        ),
        migrations.AddConstraint(
            model_name='grupoopcion',
            constraint=models.CheckConstraint(condition=models.Q(('max_selecciones__gte', 1)), name='carta_grupo_max_selecciones_positivo'),
        ),
        migrations.AddConstraint(
            model_name='grupoopcion',
            constraint=models.CheckConstraint(condition=models.Q(('seleccion_multiple', True), ('max_selecciones', 1), _connector='OR'), name='carta_grupo_simple_maximo_uno'),
        ),
        migrations.AddConstraint(
            model_name='opcionproducto',
            constraint=models.UniqueConstraint(fields=('grupo', 'nombre'), name='carta_opcion_nombre_unico_grupo'),
        ),
        migrations.AddConstraint(
            model_name='opcionproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_extra__gte', 0)), name='carta_opcion_precio_extra_no_negativo'),
        ),
    ]
