# Generated by Django 5.2.17 on 2026-10-10 07:17

import carta.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0004_grupoopcion_opcionproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP de hasta 2 MB. Ideal: WebP de unos 800 px de ancho.', upload_to=carta.models.ruta_imagen_producto, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), carta.models.validar_peso_imagen], verbose_name='imagen'),
        ),
    ]
