# Generated by Django 5.2.17 on 2026-09-17 03:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('activa', models.BooleanField(default=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.CheckConstraint(condition=models.Q(('numero__gte', 1)), name='mesas_numero_positivo')],
            },
        ),
    ]
