# Generated by Django 5.2.17 on 2026-10-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_local_mesa_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='recibe_pedidos',
            field=models.BooleanField(default=True, verbose_name='recibe pedidos por QR'),
        ),
    ]
